### ISSUE TITLE
tns run android

### ISSUE THREAD

**Issue by ghost** [tralves/nativescript-vue-rollup-template#12]
```
SyntaxError: Unexpected token import
System.err: File: "file:///data/data/org.nativescript.hellonsvue1/files/app/main.js, line: 1, column: 60
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 
System.err: SyntaxError: Unexpected token import
System.err: File: "<unknown>, line: 1, column: 265
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 	at com.tns.Runtime.runModule(Native Method)
System.err: 	at com.tns.Runtime.runModule(Runtime.java:530)
System.err: 	at com.tns.Runtime.run(Runtime.java:522)
System.err: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028)
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5658)
System.err: 	... 8 more
```

**Comment by tralves** [comment]
Hi! (sorry for the late reply, I was on vacations away from computers)

We are deprecating this template in favor of the [webpack one.](https://github.com/tralves/nativescript-vue-webpack-template). Some things may have changed and I haven't tested this template in a while.

Check the [Groceries Vue app](https://github.com/tralves/groceries-ns-vue) for an example of a working app using the webpack template.
